### ISSUE TITLE
Questions about research concept 

### ISSUE THREAD

**Issue by fonte-fs** [yorkeyao/SnP#1]
Dear author,

Thanks for  sharing codes and details of your excellent work. I really get lots of hints and try to transfer this task in other fields. But I also have some questions.

What do you think the difference between SnP task and dataset pruning is?
Can SnP be considered a training-free dataset pruning work? Or does this work need to compare with existing dataset pruning works?

Looking forward to your reply.

**Comment by yorkeyao** [comment]
Thank you for your interest in our paper! 

Yes, I think SnP can be viewed as a training-free dataset-pruning work. 

Recently, we also noticed this paper on ICLR 23. https://openreview.net/pdf?id=4wZiAXD29TQ. We are also actively studying their paper and will compare with them in our future work.

**Comment by fonte-fs** [comment]
Thanks for your answer! Hope to get more tips from you in the future.
